version: '3'
services:
  mybinder-postgres:
    container_name: mybinder-postgres
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: ${POSTGRES_USERNAME}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DATABASE: ${POSTGRES_DATABASE}
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    volumes:
      - /usr/local/mybinder-pg/data:/var/lib/postgresql/data
    command: postgres -p ${POSTGRES_PORT}
  mybinder-backend:
    container_name: mybinder-backend
    image: mybinder-backend:latest
    build: .
    environment:
      NODE_ENV: production
      PORT: ${PORT}
      DATABASE_URL: ${DATABASE_URL}
      JWT_SECRET: ${JWT_SECRET}
    ports:
      - ${PORT}:${PORT}
    depends_on:
      - mybinder-postgres
    command: sh -c "npx prisma generate && npx prisma migrate dev && npm run start"